const EXPERIENCES = {
  en: [
    { id: 1, company: 'Nsoft', title: 'Senior Full-Stack Engineer', period: 'Oct 2024 — Present', description: 'Architecting and implementing core Full-Stack solutions across distributed microservices. Designed and deployed a centralized Content Storage system (CAS) for the ecosystem. Engineered a transactional billing module and a real-time currency exchange engine. Developed complex, state-heavy user dashboards (personal cabinets) and internal admin panels with a reactive Nuxt.js UI. Optimized PostgreSQL index strategy and Redis caching for maximum scalability, while establishing automated CI/CD pipelines from scratch.' },
    { id: 2, company: 'Independent Contractor', title: 'Senior Full-Stack Software Engineer', period: 'Jan 2023 — Sep 2024', description: 'Developed scalable, event-driven backend systems for fintech platforms using Kafka and WebSockets. Implemented seamless integrations for fiat (Stripe) and crypto payment gateways. Designed a resilient, centralized logging and monitoring architecture utilizing the ELK stack. Managed containerized infrastructure and automated deployments using Docker.' }
  ],
  ru: [
    { id: 1, company: 'Nsoft', title: 'Senior Full-Stack Engineer', period: 'Окт 2024 — Наст. время', description: 'Проектирование и сквозная Full-Stack разработка распределенных сервисов. Разработал и внедрил централизованную систему хранения контента (CAS) для инфраструктуры экосистемы. Спроектировал транзакционный биллинговый модуль и реалтайм-движок котировок валют. С нуля создал сложные, нагруженные состоянием личные кабинеты пользователей и внутренние админ-панели с реактивным интерфейсом на Nuxt.js. Оптимизировал структуру индексов в PostgreSQL и кэширование в Redis для обеспечения отказоустойчивости системы, полностью автоматизировал CI/CD пайплайны.' },
    { id: 2, company: 'Independent Contractor', title: 'Senior Full-Stack Software Engineer', period: 'Янв 2023 — Сент 2024', description: 'Разработка масштабируемых event-driven бэкенд-систем для финтех-платформ с использованием Kafka и WebSockets. Реализовал интеграцию фиатных (Stripe) и криптовалютных платежных шлюзов. Спроектировал отказоустойчивую архитектуру централизованного логирования и мониторинга на базе ELK Stack. Управлял контейнеризированной инфраструктурой и автоматизацией деплоя через Docker.' }
  ],
  hy: [
    { id: 1, company: 'Nsoft', title: 'Senior Full-Stack Engineer', period: 'Հոկտ 2024 — Ներկա', description: 'Բարձր բեռնվածությամբ սերվիսների առանցքային Full-Stack ճարտարապետության նախագծում և իրականացում: Մշակել և ներդրել է բովանդակության պահպանման կենտրոնացված համակարգ (CAS) էկոհամակարգի ենթակառուցվածքի համար: Նախագծել է տրանզակցիոն բիլինգային մոդուլ և իրական ժամանակում աշխատող արժույթի փոխանակման շարժիչ: Զրոյից ստեղծել է օգտատերերի բարդ անձնական կաբինետներ և ներքին ադմինիստրատիվ վահանակներ՝ Nuxt.js-ի ռեակտիվ ինտերֆեյսով: Օպտիմալացրել է PostgreSQL ինդեքսների կառուցվածքը և Redis-ի քեշավորումը համակարգի կայունության համար, ամբողջությամբ ավտոմատացրել է CI/CD փողօղակները:' },
    { id: 2, company: 'Independent Contractor', title: 'Senior Full-Stack Software Engineer', period: 'Հուն 2023 — Սեպտ 2024', description: 'Ֆինտեք հարթակների համար մասշտաբավորվող, event-driven backend համակարգերի մշակում Kafka-ի և WebSockets-ի միջոցով: Իրականացրել է ֆիատ (Stripe) և կրիպտո վճարային դարպասների անխափան ինտեգրում: Նախագծել է կենտրոնացված լոգինգի և մոնիտորինգի կայուն համակարգ ELK Stack-ի բազայի վրա: Կառավարել է կոնտեյներացված ենթակառուցվածքները և տեղակայումները Docker-ի միջոցով:' }
  ]
}

export default defineEventHandler((event) => {
  return getLocalizedData(event, EXPERIENCES)
})
